### PR TITLE
Add shutdown key to worker's redis packet to allow remote shutdown, fixes #49

### LINKED ISSUE #46: Modifying logger behaviour
So it seems that the `verbose` option only affects the console output as far as I can tell. I had made a change to some of the logs to lower the level to `DEBUG` so I could prevent those from showing up in my logs, but it seems that there's no easy way to do that currently.

So my plan now I think, is to add a new Event that gets triggered when a log handler is loaded (thinking at line 132 in `Command.php`) which passes the log handler to the event so it can be modified before being used. This would allow customization of behaviour which would be very nice to have.

My specific use-case would be to wrap that handler with a FilterHandler (from monolog) which just limits the log level to `INFO` as minimum and returning it up.

Does this make sense? @xelan I'd appreciate the input if you have a better idea to solve this. I'll make a PR later once I have it implemented if that seems reasonable.

Other questions: what should the event constant be? We only have worker and job events right now, what would this be? I'm thinking `Event::LOG_HANDLER` is probably ok, should we start this in `3xx` series constants? I'm not sure where we should go with this.

### LINKED ISSUE #49: Unregister a worker without failing jobs?
So I'm writing logic to reload the workers automatically if my application configuration is modified. I run the below code if a configuration change is detected:

        foreach(Resque\Worker::allWorkers() as $worker) {
            $worker->unregister();
        }

This works fine for me, I run workers in docker containers and them shutting down causes the restart policy to kick in, so the containers reboot and I get a fresh set of workers.

Looking at the worker `unregister()` logic, it fails any running jobs when this happens. I'd rather get a graceful shutdown instead. I'm not entirely sure the best approach here. If I can't do it gracefully, at the very least I need to re-queue the jobs to prevent losses. A graceful shutdown would be best, so that it doesn't kill the job while it's in the middle or working. That could be bad, causing bad data states in the database or otherwise.

Any ideas? I might just need some sleep and come back to this later :stuck_out_tongue_closed_eyes:

### PR DESCRIPTION
**Pull request by francislavoie**
@mjphaynes @xelan please review

### CODE REVIEW

**Comment by mjphaynes** [comment]
The key should probably be deleted from redis during worker unregistration and clean up

**Comment by francislavoie** [comment]
It's part of the `$packet`, isn't that done already with `srem` in `unregister`? If not, what should I do?

**Comment by mjphaynes** [comment]
Ah you're right, I thought it was a new key

**Comment by xelan** [comment]
Looks good to me, thank you @francislavoie.
Just a minor thing concerning the PR title: Shouldn't it be a fix for #49 instead of #46?

**Comment by francislavoie** [comment]
Yeah, you're absolutely right.

**Comment by francislavoie** [comment]
Actually, this could probably use some documentation in the README I think to document this feature.

**Comment by xelan** [comment]
That would be great :smile: Thank you!

**Comment by francislavoie** [comment]
Wouldn't mind a quick review of the docs I just added, maybe I didn't put it in the right place?

**Comment by xelan** [comment]
In my opinion it's fine under the workers section, thank you very much @francislavoie! I've tested your feature branch and the remote shutdown works great! I'll merge next week, at the moment I'm quite busy.

**Pull request merged**
