### PR TITLE
Allow Symfony3 components, PSR-2 compliance, several bugfixes

### PR DESCRIPTION
**Pull request by xelan**
| Q             | A
| ------------- | ---
| Branch?       | master / 2.0?
| Bug fix?      | yes
| New feature?  | yes
| BC breaks?    | yes (requires Symfony components 2.7+ or 3.x, Predis 1.1.x)
| Deprecations? | no
| Fixed tickets | #28, #30, #33
| Includes PR changes | #25, #32 
| Credits | @oanhnn, @francislavoie, @xelan

This PR incorporates the changes discussed in #28 and includes the aforementioned bugfixes and improvements.

### CODE REVIEW

**Comment by mjphaynes** [comment]
Hi @xelan,

Apologies I've not been very well recently.
Since you're trying to push this project forward I've made you a collaborator :)

Also your changes look good to me - I'll leave it to you to merge and tag (will automatically sync to packagist I believe.

Cheers.

**Comment by francislavoie** [comment]
Thanks @mjphaynes for the update, hope you get well!

**Comment by xelan** [comment]
Oh, get well soon @mjphaynes! Thank you very much for your trust!

**Comment by francislavoie** [comment]
@xelan I think we should probably bring https://github.com/mjphaynes/php-resque/pull/27 into this as well, but this is an old PR, so it'll need to be cleaned up a bit to conform with PSR-2. Think we can do that before merging it?

I also added a couple other PRs, https://github.com/mjphaynes/php-resque/pull/37 should probably be merged immediately after this one and https://github.com/mjphaynes/php-resque/pull/39 is probably up for discussion as well.

When do you plan on merging this one?

I'm excited to have all of this finalized :)

**Comment by xelan** [comment]
I conducted some tests during the last days with Symfony 2.7, 2.8 and 3.2. So far, everything worked well, so I'll merge it now. Let's include the other fixes / PRs into master afterwards before tagging a 2.0 :smile:

**Pull request merged**
