### PR TITLE
add job done event

### LINKED ISSUE #53: Job Completed Event cannot access job output
Hi,

in the job completed event, you cannot access the jobs output.

I would suggest a JOB_DONE Event which should be triggered after Job output is written from output buffer to redis.

I'll add a pull request immediately

### PR DESCRIPTION
**Pull request by skors**
Add JOB_DONE Event to be triggered as last action in the perform method. This allows Event Listeners for Jobs in the short circuit processes to access job output and other packet data.

closes #53

### CODE REVIEW

**Comment by skors** [comment]
sorry, missed to squash the commits...

**Comment by xelan** [comment]
Thank you very much for your contribution, @skors! In my opinion, the new event looks good :smile:. Maybe the difference between `JOB_COMPLETE` and `JOB_DONE` should be explained a bit more in the hooks documentation.

If you want you can still squash and force-push to your feature branch - That should work on GitHub.

**Comment by skors** [comment]
okay, thank you. I'll add an info for the separations and squash the commits

**Comment by skors** [comment]
sorry, I do not get it with the squash... rebase --interactive, marked with s, there is also a new commit, but the remaining three are also there....

**Comment by xelan** [comment]
Hm, you have some local mail addresses in your commits. For squashing, I normally use a graphical editor which makes life much easier. Otherwise, you could maybe just clone the current master, create your feature branch again, overwrite with your changes and force-push to your GitHub feature branch?

Thanks!

**Comment by francislavoie** [comment]
@skors think you could finalize this?

**Comment by skors** [comment]
@francislavoie sorry, of course i'll do it

**Comment by skors** [comment]
@francislavoie it should be better now, i removed the branch, and reapply my changes and have force pushed... hopefully everything is correct

**Comment by skors** [comment]
nah, sorry... squashing...

**Pull request closed without merging**
