### PR TITLE
Feature/support read write timeout setting

### PR DESCRIPTION
**Pull request by skors**
The default timeout is 60s.
This causes failures on longer running task where the redis connection gets lost.

This PR enables configuration over the yaml config file.

For issue description see SO Discussion at http://stackoverflow.com/questions/11776029/predis-is-giving-error-while-reading-line-from-server

### CODE REVIEW

**Comment by xelan** [comment]
Thank you very much for this contribution, @skors!

I'm re-applying your changes to the current master and set you as author.
Just a short question regarding your `DEFAULT_RW_TIMEOUT` constant. You said that the default timeout is 60 seconds. Is there a specific reason why you increase the default value to 300? Maybe for people who don't have that long-running jobs the shorter (previous) default is more reasonable.

In addition to your changes in `Resque.php` and `Redis.php`, I'll adapt the `config.yml` example to include the new option.

**Comment by francislavoie** [comment]
I vote we just keep the default as 60 in the lib. No need to change the default, this lets people set their own anyways.

**Comment by skors** [comment]
@xelan you are welcome

of course, the timeout change is just some of my personal needs. you are right, keeping the default at 60s should be preferred

nice to see that working on this continues, thanks!

**Comment by xelan** [comment]
Hm, the name read_write_timeout is quite long compared to the other options. Should we change it to rw_timeout, as the constant is already `Redis::DEFAULT_RW_TIMEOUT`?

**Comment by francislavoie** [comment]
Sounds good to me.

**Comment by skors** [comment]
d`accord

**Comment by xelan** [comment]
I've merged and adapted @skors commits in a [feature branch](https://github.com/mjphaynes/php-resque/tree/feature/support-read-write-timeout-setting). Could you please review the changes and test them?

**Comment by francislavoie** [comment]
I can't test it right now, but LGTM.

**Comment by xelan** [comment]
@skors Any updates on your side? I'd like to tag release 2.0.0 next wednesday (2017-03-01), so the feature should be reviewed and integrated until then. Otherwise, it will be postponed to 2.1.0.

**Comment by skors** [comment]
@xelan sorry, was a busy week. i'll try to solve it tomorrow (monday, 20:00 CET ;-)) in the evening.

**Comment by xelan** [comment]
No problem, thank you very much!

**Comment by xelan** [comment]
Hi @skors, I already included those changes in the feature branch :wink:

Please review them there, as I needed to add e.g. a check for the new feature.
```php
if (!empty($config['rw_timeout'])) {
    $params['read_write_timeout'] = $config['rw_timeout'];
}
```
Otherwise, existing clients would break if they don't configure the new option.

You can install the feature branch for testing via composer:
```
"require": {
    "mjphaynes/php-resque": "dev-feature/support-read-write-timeout-setting as 1.3.99-dev"
}
```

**Comment by skors** [comment]
@xelan ahhh, now i got it... ;-) Are you on irc or something else?

**Comment by xelan** [comment]
Hm, would you like to user gitter? https://gitter.im/xelan-php-resque/Lobby#

**Comment by xelan** [comment]
Merged the feature branch, so I'll close this PR :smile: Thank you @skors and @francislavoie!

**Pull request closed without merging**
