### PR TITLE
Add more config extensions, job blueprint, console application and more

### LINKED ISSUE #110: Serializable interface deprecated
> 2023-02-13T14:57:52+00:00 [info] Deprecated: Resque\Helpers\SerializableClosure implements the Serializable interface, which is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary)

<sub>BTW my PR is in the progress, adding this issue just to keep track</sub>

### LINKED ISSUE #112: Unable to get code intellisense
Magic functions like `__call()` and `__callStatic()` are used pretty often in the code, and because of them IDE cant get method names and their info.

Examples of such functions can be:
```php
Resque::push() // push() is invoked via __callStatic(), function info is not loaded
```
```php
Resque\Redis::instance()->* // none of the methods of Predis\Client is loaded, makes it very complicated
```

I'm not really sure of the way to fix this, I only can think of using DocBlocks on a class with respectful `@method` fields, but that just sounds bad 😖

### PR DESCRIPTION
**Pull request by PAXANDDOS**
| Q                 | A                                            |
| ----------------- | -------------------------------------------- |
| New feature?      | Yes!                                         |
| Breaking changes? | Yes!                                         |
| Bug fix?          | Yes!                                         |
| Deprecations?     | Yes!                                         |
| Issues resolved   | _**Fixes #112**_<br />_**Fixes #110**_<br /> |

## Added

| Commit                                   | Description                                                                                                                                                                                                                                                              |
| ---------------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ |
| a8227e43e5117410257682b3a08cd1d21a0cb56e | Support for more config file extensions: `php` and `json`. This also made it possible to move symfony/yaml package from dependencies. All configuration logic is now stored in Resque\Config.                                                                            |
| 66086aaf18b3f74294f2ec473180799372799eef | Extendable console application. This makes it easier for users to run Resque commands within their own code or another Symfony Console. Also makes it easy to add their own commands. Previously application wasn't defined and its logic was dumped in the binary file. |
| d087db426b86352fa08725a99d2057feaece060b | Job blueprint which is meant to be a base for defining jobs. Users can easily get all info about methods and their arguments.<br/>`setUp` and `tearDown` functions now will receive the current Job instance.                                                            |
| 0ac1b11c27d19a4b38f6ef757bdd0949bf64ee34 | PHP DocBlocks to the main `Resque` class to help with intellisense. callStatic() breaks the intellisense in IDE's, adding respectful @method declarations of all possible methods is the only thing to make it work                                                      |
| c2f165e684a53c7fec4d14af71eeaf84135f64b6 | Added `tools/` folder which is to contain various binaries. Currently stores only PHP CS Fixer. This folder is ignored during export.                                                                                                                                    |
| 4a23ffbab88d02c051a480331023f611cd52d6c9 | Suggestions for `ext-mongodb` extension and `mongodb/mongodb` package                                                                                                                                                                                                    |

## Changed

| Commit                                   | Description                                                                                                                                                                                                                                                                                                                             |
| ---------------------------------------- | --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| 383cc7af9c5607e0cc7389e614a2622928c9da17 | Minimum PHP version is now `7.2`. Supported PHP versions are `^7.2 or ^8.0`. (I reverted the "typed properties" feature because apparently, that's a bad practice for libraries, even packages with minimum PHP version 8 don't use them. Anyway, I already got what I wanted from them, and made enough type fixes in the previous PR) |
| f74dc66f232937a7de081e6052c1057687ebf987 | Default configuration file should have the name `resque` instead of `config` (e.g. `resque.php`). Having "config" for a package in users' projects is rather confusing                                                                                                                                                                  |
| a8227e43e5117410257682b3a08cd1d21a0cb56e | Refactored structure to follow PSR-4 autoloading standard (used to follow PSR-0). Basically, I had to unwrap the `src/Resque` folder, that's where most of the file changes come from                                                                                                                                                   |
| c2f165e684a53c7fec4d14af71eeaf84135f64b6 | Improved deployment. Now only mandatory files are included in the dist package (ignored in `.gitattributes`)                                                                                                                                                                                                                            |
| c158f573732d5fb8ecd646514e7b87810781bc6a | Worker to log on a DEBUG level when no queues are found (instead of INFO). It's more of a debug information. When the user has set debug level to info and didn't add any queues, the log file will be populated every time, increasing file size, which is bad                                                                                                                                                                                                                                                                                       |
| b806a97570be2ad09404ebd7a845c7cd8cc5f986 | Bumped `predis/predis` dependency to `^2.1`                                                                                                                                                                                                                                                                                        |
| 383cc7af9c5607e0cc7389e614a2622928c9da17 | Changed `phpunit/phpunit` dependency version to `^8.0 or ^9.0`                                                                                                                                                                                                                                                                                 |
|                                          | A lot of minor improvements here and there                                                                                                                                                                                                                                                                                              |

## Deprecated

| Commit                                   | Description                                                                                                                                                                                                                                     |
| ---------------------------------------- | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| 48ac65cb086132bb42c0a9c520c9bb950e8a0cb8 | Deprecated CubeConnector (see [Monolog CubeHandler](https://github.com/Seldaek/monolog/blob/b05bf55097060ec20f49ccec0cf2f8e5aaa468b3/src/Monolog/Handler/CubeHandler.php#L23))<br>Deprecated `phpiredis` config option (see predis/predis#1179) |

## Removed

| Commit                                   | Description                                                                                                              |
| ---------------------------------------- | ------------------------------------------------------------------------------------------------------------------------ |
| 9831c1b5a1e38a86362192593c49da8e6cf7649d | Removed `Sami`, an API documentation generator. I guess it was used back in the day, it's been abandoned for a while now |

## Fixed

| Commit                                   | Description                                                                                                                                           |
| ---------------------------------------- | ----------------------------------------------------------------------------------------------------------------------------------------------------- |
| 010bc562c639110f28e58353d17b271574ffd717 | Custom configuration file not being loaded in the `SpeedTest` command                                                                                 |
| 4a23ffbab88d02c051a480331023f611cd52d6c9 | MongoDB logger connector using removed classes                                                                                                        |
| 7f8b56c7388aa2e10f3a82862b6149ad23c958c2 | `SeializableClosure` deprecation notice. Was fixed in the previous PR but since I lowered the minimum PHP version, both implementations must be added |

## Security

| Commit                                   | Description                                                  |
| ---------------------------------------- | ------------------------------------------------------------ |
| 07e879c61c45a226bf0574d89ede2eacfb4e9c43 | Added `final` keyword to classes that should not be extended |

## Tests

| PHP | PHPUnit | Manual (Console) | Manual (Web) |
| --- | ------- | ---------------- | ------------ |
| 7.2 | ✅      | ✅               | ✅           |
| 7.3 | ✅      | ✅               | ✅           |
| 7.4 | ✅      | ✅               | ✅           |
| 8.0 | ✅      | ✅               | ✅           |
| 8.1 | ✅      | ✅               | ✅           |
| 8.2 | ✅      | ✅               | ✅           |

## Post-word

And that's me again! In my previous PR I was targeting a minor release, but if we're going for v4 I decided to do everything I can to help 😄 There are some changes to make the codebase modern and also features to make usage more comfortable.
I also took care of documentation and changelog.

Also when you will be making a PR from v4 to master, you can use a [keyword with the issue number](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) as I did in this and previous PR; and when the PR is merged (to master apparently), it will close the referenced issues. I'm telling you this because I saw that you mainly use GitLab and decided to let you know

### CODE REVIEW

**Comment by xelan** [comment]
Thanks for your work, @PAXANDDOS! Concerning the supported configuration files, I saw that you deleted the `config.yml` without a replacement. I'm wondering if this might impact the learning curve of new users. Maybe we should keep the file as reference and mention how different formats can be used in the docs? I'd prefer to have a simple out-of-the-box example configuration for basic use cases.

**Comment by PAXANDDOS** [comment]
> Maybe we should keep the file as a reference and mention how different formats can be used in the docs?

It's not really gone, as I said in the PR description - just renamed (`config.yml` -> `resque.yml`  _+ formats_). Because resque is meant to be used in other people's projects, and having a `config.yml` in their project root would be somewhat confusing: is it for the project or a package? 

Or do you mean that we should keep both the "config" and "resque" files? That would make sense if we are to deprecate the file, but it's the major release anyway

**Comment by PAXANDDOS** [comment]
@xelan Are there any other questions? I believe I described everything in the description

**Comment by xelan** [comment]
:shipit: 

> @xelan Are there any other questions? I believe I described everything in the description

Thanks, your description looks good, I just need a bit of time to review the PR.

**Comment by PAXANDDOS** [comment]
Bump 👀

**Comment by xelan** [comment]
Concerning the removal of Sami for doc generation - what would you think about using the [maintained fork Doctum](https://github.com/code-lts/doctum) instead? Generated API doc is still useful IMHO.
Thanks!

**Comment by PAXANDDOS** [comment]
Sorry for the late response.

The tool seems great! I'm not sure if Resque would need it though, the project is not really big. If you wanna target the contributors then DocBlocks within the code should be good. To be fair, I haven't seen many open-source packages using generated API docs. If you still wanna use then maybe we can delay that for v4.1 or something like that? 

I just really hope to see current changes in production soon but unfortunately can't do any more contributions for now, got to finish my graduate program

**Comment by PAXANDDOS** [comment]
Bump!

**Comment by xelan** [comment]
> Bump!

Hi @PAXANDDOS, I‘m currently out of office and back next week.

Best regards
Andreas

**Pull request merged**
