### PR TITLE
fix PHP Notice:  A non well formed numeric value encountered

### PR DESCRIPTION
**Pull request by MiRacLe-RPZ**

### CODE REVIEW

**Comment by xelan** [comment]
Thank you very much for your contribution, @MiRacLe-RPZ! Do you know which value(s) passed to `Resque\Helpers\Util::human_time_diff()` cause the PHP notice?

**Comment by MiRacLe-RPZ** [comment]
> 127.0.0.1:6379> HGETALL namespace:worker:hostname:pid
>  1) "started"
>  2) "1605689021,3478" <--- HERE
> ...

**Comment by xelan** [comment]
> 
> 
> > 127.0.0.1:6379> HGETALL namespace:worker:hostname:pid
> > 
> > 1. "started"
> > 2. "1605689021,3478" <--- HERE
> >    ...
> 
> the system locale is not "C", the decimal separator is comma, the problem is wider than I thought ...

Oh, so apparently casts of float to string lead to the invalid decimal separator in Redis. Redis values are always transmitted as strings, that's probably why it ended up like that. Could you try to reset your locale for PHP before enqueuing the worker job?

**Comment by MiRacLe-RPZ** [comment]
> Could you try to reset your locale for PHP before enqueuing the worker job?

Yes, i can `setlocale(LC_NUMERIC, 'C')` before start worker, before enqueue job, before ... , but locale can be changed by job's code: https://i.imgur.com/izGiR59.png (sorry, "code" as picture)

Maybe use getArray() methods instead of getPacket code like Job::execTime, Workers::execute, etc?

**Comment by xelan** [comment]
By using `setlocale()`, any libraries casting floats to string may show unexpected behavior. Other than that, the locales are set [per process, not per thread](https://www.php.net/setlocale) so there might even be unintended side effects to other scripts which do not call setlocale() at all!
See the discussion PHP internals: https://externals.io/message/103638#103669

How / for which purposes are you using `setlocale()`? Maybe there are better, modern alternative such as [PHP-Intl](https://www.php.net/manual/de/book.intl.php) or the [Symfony Intl component](https://symfony.com/doc/current/components/intl.html)?

Best regards from Austria
Andreas

**Comment by MiRacLe-RPZ** [comment]
> How / for which purposes are you using setlocale()

Notice from subject was catched on machine with non-english system-wide locale (without calling `setlocale` in "my" code).

I'm understand "global" problem with locale, but i can't control environment of my users... Close PR, i'll be back with another patch later. Thx for deep looking ;)

**Comment by xelan** [comment]
Thank you very much for bringing this up! For properly fixing this issue, we'd need to evaluate where exactly the floats are converted to the Redis string values. Beside the "cosmetic" problem of wrong timestamp display, business logic which acts on job data (e.g. duration, age, ...) might be severely affected by the invalid float strings. However, I'm not sure whether we can do a lot about this. However, I'm not sure whether this issue can be fixed by the lib, as the root cause is in PHPs string casting, which uses localized instead of non-localized number formats.

**Pull request closed without merging**
