### PR TITLE
Change composer suggest to phpiredis

### PR DESCRIPTION
**Pull request by francislavoie**
As per changes from https://github.com/mjphaynes/php-resque/pull/36

### CODE REVIEW

**Comment by xelan** [comment]
Thank you, @francislavoie! As far as I can tell, the [Redis PHP extension](https://pecl.php.net/package/redis) is [still actively maintained](https://github.com/phpredis/phpredis/releases). So I'd suggest to leave both alternatives in the `README` and `composer.json` and maybe explain their differences shortly. What do you think?

**Comment by francislavoie** [comment]
No, we use Predis as a dependency, they used to suggest phpredis but now binds with phpiredis in the current version. Having phpredis won't make any difference anymore for resque (unless I missed something).

**Comment by xelan** [comment]
As far as I can tell [from the docs](https://github.com/nrk/predis/blob/v1.1/FAQ.md#if-i-need-an-extension-to-get-better-performances-why-not-using-phpredis), phpredis is still supported, but phpiredis is recommended.

**Comment by francislavoie** [comment]
Hmm, I did miss that note in their docs. It does seem to me like the later after reading some more. Looking at some of the PRs and issues, Predis has the goal of keeping an API compatible with `phpredis`, but uses `phpiredis` as an accelerator to itself. So I think that `phpredis` will do nothing. Do you have an environment in which you could test that theory easily? I can't do it right now but I could look into it later when I'm at work (I use Docker so I could swap out the extension in my Dockerfile and compare speeds).

**Comment by francislavoie** [comment]
How about this - we merge this one for now, and I'll open an issue for us to take a look at if `phpredis` actually does anything with Predis.

**Comment by xelan** [comment]
Hm, I'd check it first if it doesn't take long to avoid confusion among users of php-resque. As it is "just" documentation, the phpiredis extension can be used right now anyway if necessary.

**Comment by francislavoie** [comment]
That's what I mean, we can add the `phpredis` suggest back in once tested. I won't be able to try it for a few days at least. It's a holiday today in Canada so I'm home, and I have higher priorities at work to get to first. I think we should at least have this documentation in for the 2.0 release because we added that `phpiredis` config support.

**Comment by xelan** [comment]
Ah, ok :smile: Well, then I'll merge it now. Have a nice holiday!

**Pull request merged**
