### PR TITLE
[ Feature ] Retry

### PR DESCRIPTION
**Pull request by merlindorin**
Hi,

I'm working on a draft of this feature #73 ... in fact, if my test succeed, I'm ready to PR something more relevant. :D

In this commit, I just add a quick doc of the related feature... with a dirty english (as usual 😢 ).

If you have question or suggestion, don't hesitate. Everything is welcome ^^.

### CODE REVIEW

**Comment by iam-merlin** [comment]
Btw, if you want test, if possible, I need my previous PR to be reviewed.

**Comment by iam-merlin** [comment]
it works :D

screen shot 2017-12-19 at 20 10 56

**Comment by xelan** [comment]
Great! Then I'd say let's get #72 ready first and then this one :smile:

**Comment by iam-merlin** [comment]
indeed and done

**Comment by scones** [comment]
stall this until #81 ?

**Comment by iam-merlin** [comment]
yes I think

**Pull request closed without merging**
