### PR TITLE
Symfony v4 beta

### PR DESCRIPTION
**Pull request by MaximeMaillet**
#70

### CODE REVIEW

**Comment by xelan** [comment]
Hi @MaximeMaillet! Thank you for your PR!

Your current approach would prohibit the usage of Symfony 3, it should be `~2.7|~3.0|~4.0.0` instead. Or even better, just `~2.7|~3.0|~4.0` to allow 2.7 and higher Symfony 2 versions, 3.0 and higher Symfony 3 versions, and 4.0 and higher Symfony 4 versions.

By the way, did you check that all used method calls/classes/... are compatible between Symfony 2, 3 and 4?

**Comment by iam-merlin** [comment]
@xelan from my point of view, trying to get a compatibility across Symfony's versions is hazardous without a bench of test. The main reason is not the initial work (which is quite intensive), it's mainly for the code maintainability. 

Any simple piece of code have to be review across version. This point will limit any enhancements and new features.

Maybe we can add as requirement the write of test for any new feature/enhancement. I can write a `.travis.yml` if you need a starting point.

Just a point of view ;).

**Comment by xelan** [comment]
Right, that's why the last PR integrating support for Symfony 3.x took quite some time and also manual testing effort. Having a comprehensive test suite would defintely help a lot! See [#26](https://github.com/mjphaynes/php-resque/issues/26) for the discussion about that. 

Thank you very much for your offer to help with creating a test suite. In my opinion, it would be best to start with a test suite now even before the changes for 4.x to detect and mitigate possible compatiblity issues.

**Comment by iam-merlin** [comment]
blocked by #72 ;) (I will finished my PR tomorrow ;) )

**Comment by iam-merlin** [comment]
Following #78, if people are agreed, I think we can delete this PR or move it to a new repo like `php-resque-cli`

**Comment by xelan** [comment]
@mjphaynes What do you think about the separation of the php-resque core from the CLI? Now that Symfony 4 is entering LTS soon and 5 to be released shortly, this becomes more important IMHO.

**Comment by xelan** [comment]
Any news @mjphaynes? As Symfony 5 is gaining traction, proper support seems to become more important for this project as well. By the way, maybe we should also re-evaluate the minimum requirements (e.g. go to 7.1+?)

**Comment by xelan** [comment]
Implemented in php-resque v3 :+1: :partying_face:

**Pull request closed without merging**
